name: Mirror to Gitee and Build Gitee Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@matster
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
            source-repo: git@github.com:yilunyuwan/rui-react.git
            destination-repo: git@gitee.com:yilunyuwan/rui-react.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: yilunyuwan
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: yilunyuwan/rui-react
          branch: gh-pages